markdown: kramdown
name: "Jalisco Cómo Votamos 2018"
url: https://jaliscocomovotamos.netlify.com
encoding: utf-8
timezone: America/Mexico_City
lang: es-MX
description: "Conoce a las y los candidatos en las elecciones locales, estatales y nacionales en el estado de Jalisco, México. Jalisco Cómo Votamos es un proyecto del observatorio ciudadano Jalisco Cómo Vamos."
plugins_dir:
  - jekyll-redirect-from
email: "vicki.foss@gmail.com"
