markdown: kramdown
name: "Jalisco Cómo Votamos 2018"
url: 
encoding: utf-8
timezone: America/Mexico_City
lang: es-MX
description: "Conoce a los candidatos federales, estatales y locales en el estado de Jalisco, México."
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyCCHOtkHXgr5YvKnfLlXe9ZOFEmSQbVrQU
